
import Common.OpenPdf;
import Dao.ConnectionProvider;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.*;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.table.TableModel;
import Dao.PharmacyUtils;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfPTable;
import java.io.FileOutputStream;
import com.itextpdf.text.pdf.PdfWriter;
import java.io.File;
import java.util.Date;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author SR Laptop
 */
public class SellMedicine extends javax.swing.JFrame {
public String numberPattern="[0-9]+";
private int finalTotalPrice=0;
private String billID="";
private String username="";
    /**
     * Creates new form SellMedicine
     */
    public SellMedicine() {
        initComponents();
    }
    public SellMedicine(String tempUsername) {
           initComponents();
           username=tempUsername; //store current username
           setLocationRelativeTo(null);
    }
    private void medicineName(String nameOrUniqueId){
        DefaultTableModel model=(DefaultTableModel) medicinesTable.getModel();
        model.setRowCount(0);
        try{
            Connection con=ConnectionProvider.getCon();
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("SELECT * FROM medicine WHERE name LIKE '" + nameOrUniqueId + "%' OR UniqueId LIKE '" + nameOrUniqueId + "%'");//it search medicines table where name or uniqueId  starts with  on user input.
            while(rs.next()){
                model.addRow(new Object[]{rs.getString("uniqueId")+"-"+ rs.getString("name")});
                
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }    
    }
    private void clearMedicineFields(){
        txtUniqueId.setText("");
        txtName.setText("");
        txtCompanyName.setText("");
        txtPricePerUnit.setText("");
        txtNoOfUnits.setText("");
        txtTotalPrice.setText("");
    }
    public String getUniqueId(String prefix){
        return prefix+System.nanoTime();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        medicinesTable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        txtUniqueId = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtCompanyName = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtPricePerUnit = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtNoOfUnits = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtTotalPrice = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        cartTable = new javax.swing.JTable();
        btnAddToCart = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        lblFinalTotalPrice = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Sell Medicine");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(581, 0, -1, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 54, 1360, -1));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/close.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 10, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Search");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(217, 89, 57, -1));

        txtSearch.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchActionPerformed(evt);
            }
        });
        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchKeyReleased(evt);
            }
        });
        getContentPane().add(txtSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 116, 300, -1));

        medicinesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Medicine"
            }
        ));
        medicinesTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                medicinesTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(medicinesTable);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 149, 300, 540));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Medicine ID");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 100, -1, -1));

        txtUniqueId.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(txtUniqueId, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 130, 300, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Name");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 170, 48, -1));

        txtName.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 210, 300, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Company Name");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 270, 99, -1));

        txtCompanyName.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(txtCompanyName, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 300, 300, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Price Per Unit");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 100, -1, -1));

        txtPricePerUnit.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(txtPricePerUnit, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 130, 300, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("No. of Units");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 180, -1, -1));

        txtNoOfUnits.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtNoOfUnits.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNoOfUnitsKeyReleased(evt);
            }
        });
        getContentPane().add(txtNoOfUnits, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 210, 300, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Total Price");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 270, 84, -1));

        txtTotalPrice.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(txtTotalPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 300, 300, -1));

        cartTable.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cartTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Medicine Id", "Name", "Company Name", "Price Per Unit", "No. Of Units", "Total Price"
            }
        ));
        cartTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cartTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(cartTable);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 380, 681, 270));

        btnAddToCart.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnAddToCart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add to cart.png"))); // NOI18N
        btnAddToCart.setText("Add to Cart");
        btnAddToCart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddToCartActionPerformed(evt);
            }
        });
        getContentPane().add(btnAddToCart, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 340, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("RS:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 660, -1, -1));

        lblFinalTotalPrice.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblFinalTotalPrice.setForeground(new java.awt.Color(255, 255, 255));
        lblFinalTotalPrice.setText("00");
        getContentPane().add(lblFinalTotalPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 660, 59, -1));

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/generate bill & print.png"))); // NOI18N
        jButton3.setText("Purchase & Print");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 660, -1, -1));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/adminDashboardBackground.png"))); // NOI18N
        jLabel12.setText("jLabel12");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    setVisible(false);       // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed
//Add selected medicine into the cart after selection
    private void btnAddToCartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddToCartActionPerformed
              setVisible(true);                              
    // TODO add your handling code here:
    // user must select these two fields
    String noOfUnits = txtNoOfUnits.getText();
    String uniqueId = txtUniqueId.getText();
    //ensures if both fields are filled
   if(!noOfUnits.equals("") && !uniqueId.equals("")){
       //get medicine detail
        String name = txtName.getText();
        String companyName = txtCompanyName.getText();
        String pricePerUnit = txtPricePerUnit.getText();
        String totalPrice = txtTotalPrice.getText();
        int checkStock = 0;
        int checkMedicineAlreadyExistInCart = 0;
     //check from stock
        try{
            Connection con = ConnectionProvider.getCon(); 
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("select *from medicine where uniqueId="+uniqueId+"");
            while(rs.next()){
                if(rs.getInt("quantity") >= Integer.parseInt(noOfUnits)){
        checkStock = 1;
    }else{
        JOptionPane.showMessageDialog(null, "Medicine is out of stock. Only "+rs.getInt("quantity")+" Left");
    }
        }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        if(checkStock == 1){
    DefaultTableModel dtm = (DefaultTableModel) cartTable.getModel();
//medicine already in the cart
for (int i = 0; i < dtm.getRowCount(); i++) {

    Object cellValue = dtm.getValueAt(i, 0);

    if (cellValue != null) {   // ✅ NULL CHECK
        String tableUniqueId = cellValue.toString();

        if (tableUniqueId.equals(uniqueId)) {
            checkMedicineAlreadyExistInCart = 1;
            JOptionPane.showMessageDialog(null, "Medicine already exists in cart");
            break;
        }
    }
}
//add items into the cart table
    if(checkMedicineAlreadyExistInCart==0){
        dtm.addRow(new Object[]{uniqueId,name,companyName,pricePerUnit, noOfUnits,totalPrice});
        //update total bill
        finalTotalPrice=finalTotalPrice + Integer.parseInt(totalPrice);
        lblFinalTotalPrice.setText(String.valueOf(finalTotalPrice));
        JOptionPane.showMessageDialog(null,"Added Successfully");
    
       // TODO add your handling code here:
    }//GEN-LAST:event_btnAddToCartActionPerformed
    clearMedicineFields(); // clear meidcine fields
    
    
        }
        
    }
    else{
        JOptionPane.showMessageDialog(null,"No of units and medicine field is required");
    }
    }
    // saves bill and generate bill
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
    if(finalTotalPrice!=0){ //only proceed if cart is not empty     // TODO add your handling code here:
        billID=getUniqueId("Bill-"); //generate bill Id
        DefaultTableModel dtm=(DefaultTableModel)cartTable.getModel();
        if(cartTable.getRowCount()!=0){
            for(int i=0;i<cartTable.getRowCount();i++){
                try{
                Connection con=ConnectionProvider.getCon();
                Statement st=con.createStatement();
                //update stock in database. Reduces stock after 
                st.executeUpdate("update medicine set quantity=quantity-"+Integer.parseInt(dtm.getValueAt(i,4).toString())+" where uniqueId="+Integer.parseInt(dtm.getValueAt(i,0).toString()));
                
                }
                catch(Exception e)
                {
                    JOptionPane.showMessageDialog(null,e);
                }
                
            }
            
        }
        try{
            SimpleDateFormat myFormat=new SimpleDateFormat("dd-MM-yyyy");
            Calendar cal=Calendar.getInstance();
            Connection con=ConnectionProvider.getCon();
            //save bill in database
            PreparedStatement ps=con.prepareStatement("INSERT INTO Bill(billId,billDate,totalPaid,generatedBy) VALUES(?,?,?,?)");
            ps.setString(1,billID);
            ps.setString(2,myFormat.format(cal.getTime()));
            ps.setInt(3,finalTotalPrice);
           ps.setString(4, UserSession.username);
            ps.executeUpdate();
            
            
            
        }
        catch(Exception e){
           
            JOptionPane.showMessageDialog(null,e);
        }
        //create Bill
        com.itextpdf.text.Document doc =new com.itextpdf.text.Document();
        try{
             // ✅ ADD THIS PART HERE
    File dir = new File(PharmacyUtils.billPath);
    if (!dir.exists()) {
        dir.mkdirs();
    }
            PdfWriter.getInstance(doc,new FileOutputStream(PharmacyUtils.billPath+""+billID+".pdf"));
            doc.open();
            Paragraph pharmacyName=new Paragraph("                                  Pharmacy Management System\n");
            doc.add(pharmacyName);
            Paragraph starLine=new Paragraph("*************************************************************");
            doc.add(starLine);
            Paragraph details =new Paragraph("\tBill ID: "+billID+"\nDate: "+ new Date()+"\nTotal Paid: "+finalTotalPrice);
            doc.add(details);
            doc.add(starLine);
            PdfPTable tb1=new PdfPTable(6);
            tb1.addCell("Medicine ID");
            tb1.addCell("Name");
            tb1.addCell("Company Name");
            tb1.addCell("Price Per Unit");
            tb1.addCell("No. of Units");
            tb1.addCell("Sub Total Price");
            for(int i=0;i<cartTable.getRowCount();i++){
                String a=cartTable.getValueAt(i, 0).toString();
                String b=cartTable.getValueAt(i, 1).toString();
                String c=cartTable.getValueAt(i, 2).toString();
                String d=cartTable.getValueAt(i, 3).toString();
                String e=cartTable.getValueAt(i, 4).toString();
                String f=cartTable.getValueAt(i, 5).toString();
                tb1.addCell(a);
                 tb1.addCell(b);
                  tb1.addCell(c);
                   tb1.addCell(d);
                    tb1.addCell(e);
                     tb1.addCell(f);   
            }
            doc.add(tb1);
            doc.add(starLine);
            Paragraph thankMsg=new Paragraph("Thank You.");
            doc.add(thankMsg);
            OpenPdf.openById(String.valueOf(billID));
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
        doc.close();
        setVisible(false);
        new SellMedicine(username).setVisible(true);
        
        
        
    }
    else{
    JOptionPane.showMessageDialog(null,"Please add some medicines to cart.");
    }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
    medicineName("");
    txtUniqueId.setEditable(false);
        txtName.setEditable(false);
        txtCompanyName.setEditable(false);
        txtPricePerUnit.setEditable(false);
        txtNoOfUnits.setEditable(true);
        txtTotalPrice.setEditable(true);// TODO add your handling code here:
    }//GEN-LAST:event_formComponentShown

    private void txtSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyReleased
    String search=txtSearch.getText();
    medicineName(search);// TODO add your handling code here:
    }//GEN-LAST:event_txtSearchKeyReleased

    private void medicinesTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_medicinesTableMouseClicked
    int index= medicinesTable.getSelectedRow();
    TableModel model=medicinesTable.getModel();
    String nameOrUniqueId=model.getValueAt(index,0).toString();
    String UniqueId[]=nameOrUniqueId.split("-",0);
    try{
    Connection con=ConnectionProvider.getCon();
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("SELECT * FROM medicine WHERE uniqueId="+UniqueId[0]+"");
            while(rs.next())
            {
              txtUniqueId.setText(UniqueId[0]);
        txtName.setText(rs.getString("name"));
        txtCompanyName.setText(rs.getString("CompanyName"));
        txtPricePerUnit.setText(rs.getString("price"));
        txtNoOfUnits.setText("");
        txtTotalPrice.setText("");  
            }
}
    catch(Exception e){
    JOptionPane.showMessageDialog(null,e);
}
    }//GEN-LAST:event_medicinesTableMouseClicked

    private void txtNoOfUnitsKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNoOfUnitsKeyReleased
    String NoOfUnits=txtNoOfUnits.getText();
    if(!NoOfUnits.equals("")){
String price=txtPricePerUnit.getText();
if(!NoOfUnits.matches("[0-9]+")){
    JOptionPane.showMessageDialog(null,"Number of Units are invalid");    
}
int TotalPrice=Integer.parseInt(NoOfUnits)*Integer.parseInt(price);
txtTotalPrice.setText(String.valueOf(TotalPrice));
    }//GEN-LAST:event_txtNoOfUnitsKeyReleased
else
    {
        txtTotalPrice.setText("");
    }
    }
    private void cartTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cartTableMouseClicked
     int index=cartTable.getSelectedRow();
     int a=JOptionPane.showConfirmDialog(null,"Do you want to remove this medicine","SELECT",JOptionPane.YES_NO_OPTION);
if(a==0){
    TableModel model=cartTable.getModel();
    String total=model.getValueAt(index,5).toString();
    finalTotalPrice=finalTotalPrice-Integer.parseInt(total);
    lblFinalTotalPrice.setText(String.valueOf(finalTotalPrice));
    ((DefaultTableModel) cartTable.getModel()).removeRow(index);
    }//GEN-LAST:event_cartTableMouseClicked
    }
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SellMedicine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SellMedicine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SellMedicine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SellMedicine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SellMedicine().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddToCart;
    private javax.swing.JTable cartTable;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblFinalTotalPrice;
    private javax.swing.JTable medicinesTable;
    private javax.swing.JTextField txtCompanyName;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtNoOfUnits;
    private javax.swing.JTextField txtPricePerUnit;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtTotalPrice;
    private javax.swing.JTextField txtUniqueId;
    // End of variables declaration//GEN-END:variables
}
